module UiStr
  DISPLAY_NONE            = "display: none"
  DISPLAY_INLINE          = "display: inline-block"
  ERROR_TAG               = "Error"
  NEW_QTY_TAG             = "new_quantity"
  SCRN_UNAVAILABLE        = "Screen unavailable"

  WARNING_IMG             = "warning.png"
  EXCLAMATION_IMG         = "exclamation-red.png"
  SOFT_DASH_IMG           = "soft-dash.png"
  CHECK_GREEN_IMG         = "check-green.png"
  MAG_PLUS_IMG            = "mag-plus.png"
  MAG_MINUS_IMG           = "mag-minus.png"
  ICON_PRINTER_IMG        = "icons/printer.png"

  CONFIRMED_TAG           = "Confirmed"
  UNCONFIRMED_TAG         = "Unconfirmed"
  NO_BID_REQUIRED_TAG     = "No bid required"
  MAG_PLUS_TAG            = "mag-plus"
  MAG_MINUS_TAG           = "mag-minus"
  NOTICE_TAG              = "Notice"
  UNSUBMITTED_TAG         = "Unsubmitted"
  PRINTER_TAG             = "printer"

  STRING_TBLFRMT          = "string"
  EXACT_NUMBER_TBLFRMT    = "exact-number"
  CURRENCY_TBLFRMT        = "currency"
  NUMBER_TBLFRMT          = "number"
  PERCENTAGE_TBLFRMT      = "percentage"
  CHKBOX_TBLFRMT          = "checkbox"
  IMAGE_URL               = "image-url"
  LINK_TBLFRMT            = "link"

  PUBLISHER               = "Publisher"
  TITLE                   = "Title"
  RESERVE_PRICE           = "Reserve Price"
  SUPPLY                  = "Supply"
  UNITS                   = "Units"
  DEMAND                  = "Demand"
end
